# Generated by Django 5.2.7 on 2025-11-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MentionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Mention",
            fields=[
                (
                    "item_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("platform", models.CharField(max_length=255)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("suggester", models.CharField(max_length=255, null=True)),
                ("raw_data", models.JSONField()),
            ],
            options={
                "ordering": ["-processed_at"],
                "indexes": [
                    models.Index(
                        fields=["platform"], name="trackers_me_platfor_8d1029_idx"
                    )
                ],
            },
        ),
    ]
